/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin' at '11/5/16 7:06 PM' with Gradle 3.1
 *
 * @author admin, @date 11/5/16 7:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
